# Array Basics
<h3 style="font-family:Courier;font-size:10px;">Converted to Python3</h3>

In [9]:
import numpy as np
my_list1 = [1,2,3,4]
my_array1 = np.array(my_list1)
my_array1

array([1, 2, 3, 4])

In [10]:
my_list2 = [11,22,33,34]
my_lists = [my_list1,my_list2]
my_lists

[[1, 2, 3, 4], [11, 22, 33, 34]]

## Create a multidimensional array

In [11]:
my_array2 = np.array(my_lists)
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 34]])

In [13]:
#shape method (defines structure)
print(my_array2.shape)
#dtype method shows data type of array
print(my_array2.dtype)

(2, 4)
int32


In [14]:
#Built in array methods
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [15]:
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [17]:
#Empty method will also create an array of zeros
varr = np.empty(5)
print(varr)
type(varr)

[ 0.  0.  0.  0.  0.]


numpy.ndarray

In [19]:
#Create an identity matrix with eye method
print(np.eye(5))
np.eye(2)

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


array([[ 1.,  0.],
       [ 0.,  1.]])

# Using Arrays w/ Scalars
## mathematical operations w/ arrays

In [20]:
5/2

2.5

In [22]:
from __future__ import division #if using v.2.7
5/2

2.5

In [23]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

In [24]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [25]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [26]:
arr1+arr1
arr1[1][2]
arr1[0][1]

2

In [27]:
1 / arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.125     ,  0.11111111,  0.1       ,  0.09090909]])

In [28]:
arr1 ** 3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]], dtype=int32)

# Indexing Arrays

In [29]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
#arrays are indexed like Python lists
arr[0],arr[1]

(0, 1)

In [31]:
arr[1:5]

array([1, 2, 3, 4])

In [32]:
arr2 = np.array([np.arange(1,5),np.arange(2,6)])

In [33]:
arr2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [34]:
type(arr2)

numpy.ndarray

In [35]:
arr2[1][0],arr2[0][2]

(2, 3)

In [36]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [37]:
arr = np.arange(0,11)

In [38]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [39]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [40]:
#in Numpy, Data isn't copied.  It's a view of the original array...
#See now that the original array has been changed after the slice has been changed.
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [41]:
#if you don't want that to happen, you explicitly have to make a copy
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [42]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [43]:
#Show row 1
arr_2d[1]

array([20, 25, 30])

In [44]:
#Individual element
arr_2d[1][0]

20

# 2d Array Slicing

In [45]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

# Fancey Indexing

In [46]:
arr2d = np.zeros((10,10))
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [47]:
arr_length = arr2d.shape[1]
arr_length

10

In [48]:
for i in range(arr_length):
    arr2d[i]=i*2
arr2d

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  2.,   2.,   2.,   2.,   2.,   2.,   2.,   2.,   2.,   2.],
       [  4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.],
       [  6.,   6.,   6.,   6.,   6.,   6.,   6.,   6.,   6.,   6.],
       [  8.,   8.,   8.,   8.,   8.,   8.,   8.,   8.,   8.,   8.],
       [ 10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.],
       [ 12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 14.,  14.,  14.,  14.,  14.,  14.,  14.,  14.,  14.,  14.],
       [ 16.,  16.,  16.,  16.,  16.,  16.,  16.,  16.,  16.,  16.],
       [ 18.,  18.,  18.,  18.,  18.,  18.,  18.,  18.,  18.,  18.]])

In [49]:
#Fancy indexing lets us list the rows we want displayed by their numerical index
arr2d[[2,4,6,8]]

array([[  4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.],
       [  8.,   8.,   8.,   8.,   8.,   8.,   8.,   8.,   8.,   8.],
       [ 12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 16.,  16.,  16.,  16.,  16.,  16.,  16.,  16.,  16.,  16.]])