# Merging Datasets[29]
## Linking Rows by Keys
<h3 style="font-family:Courier;font-size:10px;">Converted for Python3</h3>

In [4]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [15]:
#Create DataFrame from dictionary and np.arange
dframe1 = DataFrame({'key':['X','Z','Y','Z','X','X'],'data_set_1':np.arange(6)},index=['a','b',
                                                                                      'c',
                                                                                      'd','d','e'])
dframe1

data_set_1 key
a           0   X
b           1   Z
c           2   Y
d           3   Z
d           4   X
e           5   X

In [16]:
dframe2 = DataFrame({'key':['Q','Y','Z'],'data_set_2':[1,2,3]})
dframe2

data_set_2 key
0           1   Q
1           2   Y
2           3   Z

In [17]:
#Use the merge method (many to one): automatically overlaps where keys match
pd.merge(dframe1,dframe2)

data_set_1 key  data_set_2
0           1   Z           3
1           3   Z           3
2           2   Y           2

In [18]:
#merge on a specific column
pd.merge(dframe1,dframe2,on='key')

data_set_1 key  data_set_2
0           1   Z           3
1           3   Z           3
2           2   Y           2

In [19]:
#Choose which keys to use
pd.merge(dframe1,dframe2,on='key',how='left')

data_set_1 key  data_set_2
0           0   X         NaN
1           1   Z         3.0
2           2   Y         2.0
3           3   Z         3.0
4           4   X         NaN
5           5   X         NaN

In [20]:
pd.merge(dframe1,dframe2,on='key',how='right')

data_set_1 key  data_set_2
0         1.0   Z           3
1         3.0   Z           3
2         2.0   Y           2
3         NaN   Q           1

In [21]:
#Create a union of both keys
pd.merge(dframe1,dframe2,on='key',how='outer')

data_set_1 key  data_set_2
0         0.0   X         NaN
1         4.0   X         NaN
2         5.0   X         NaN
3         1.0   Z         3.0
4         3.0   Z         3.0
5         2.0   Y         2.0
6         NaN   Q         1.0

### Make a many to many merge

In [22]:
dframe3 = DataFrame({'key':['X','X','X','Y','Z','Z'],'data_set_3':range(6)})

In [23]:
dframe4 = DataFrame({'key':['Y','Y','X','X','Z'], 'data_set_4':range(5)})

In [24]:
dframe3

data_set_3 key
0           0   X
1           1   X
2           2   X
3           3   Y
4           4   Z
5           5   Z

In [25]:
dframe4

data_set_4 key
0           0   Y
1           1   Y
2           2   X
3           3   X
4           4   Z

In [26]:
pd.merge(dframe3,dframe4)

data_set_3 key  data_set_4
0           0   X           2
1           0   X           3
2           1   X           2
3           1   X           3
4           2   X           2
5           2   X           3
6           3   Y           0
7           3   Y           1
8           4   Z           4
9           5   Z           4

In [27]:
#Merge with multiple keys
df_left = DataFrame({'key1':['SF','SF','LA'],
                     'key2':['one','two','one'],
                     'left_data':[10,20,30]})

In [28]:
df_right = DataFrame({'key1':['SF','SF','LA','LA'],
                     'key2':['one','one','one','two'],
                     'right_data':[40,50,60,70]})

In [29]:
df_left

key1 key2  left_data
0   SF  one         10
1   SF  two         20
2   LA  one         30

In [30]:
df_right

key1 key2  right_data
0   SF  one          40
1   SF  one          50
2   LA  one          60
3   LA  two          70

In [31]:
#Merge on multiple keys
pd.merge(df_left,df_right,on=['key1','key2'],how='outer')

key1 key2  left_data  right_data
0   SF  one       10.0        40.0
1   SF  one       10.0        50.0
2   SF  two       20.0         NaN
3   LA  one       30.0        60.0
4   LA  two        NaN        70.0

In [32]:
#Pandas can automatically add suffixes if two columns share a name
pd.merge(df_left,df_right,on='key1')

key1 key2_x  left_data key2_y  right_data
0   SF    one         10    one          40
1   SF    one         10    one          50
2   SF    two         20    one          40
3   SF    two         20    one          50
4   LA    one         30    one          60
5   LA    one         30    two          70

In [33]:
#What if we want to specify a suffix
pd.merge(df_left,df_right,on='key1',suffixes=('_lefty','_righty'))

key1 key2_lefty  left_data key2_righty  right_data
0   SF        one         10         one          40
1   SF        one         10         one          50
2   SF        two         20         one          40
3   SF        two         20         one          50
4   LA        one         30         one          60
5   LA        one         30         two          70

## Merge parameters in Pandas documentation
url = 'http://pandas.pydata.org/pandas-docs/dev/generated/pandas.DataFrame.merge.html'

# Merge on Index

In [34]:
df_left = DataFrame({'key':['X','Y','Z','X','Y'],
                    'data':range(5)})
df_left

data key
0     0   X
1     1   Y
2     2   Z
3     3   X
4     4   Y

In [35]:
df_right = DataFrame({'group_data':[10,20]},index=['X','Y'])
df_right

group_data
X          10
Y          20

In [36]:
#Use index for right, and key for left DataFrame
#Every x in group data is a 10, every y is a 20
pd.merge(df_left,df_right,left_on='key',right_index=True)

data key  group_data
0     0   X          10
3     3   X          10
1     1   Y          20
4     4   Y          20

In [37]:
#Use a hierarchy index with merging
df_left_hr = DataFrame({'key1':['SF','SF','SF','LA','LA'],
                       'key2':[10,20,30,20,30],
                       'data_set':np.arange(5)})
df_left_hr

data_set key1  key2
0         0   SF    10
1         1   SF    20
2         2   SF    30
3         3   LA    20
4         4   LA    30

In [38]:
df_right_hr = DataFrame(np.arange(10).reshape(5,2),
                       index=[['LA','LA','SF','SF','SF'],
                             [20,10,10,10,20]],
                       columns=['col_1','col_2'])

In [39]:
df_right_hr

col_1  col_2
LA 20      0      1
   10      2      3
SF 10      4      5
   10      6      7
   20      8      9

In [40]:
#Merge the left using keys and the right by index
pd.merge(df_left_hr,df_right_hr,left_on=['key1','key2'],right_index=True)

data_set key1  key2  col_1  col_2
0         0   SF    10      4      5
0         0   SF    10      6      7
1         1   SF    20      8      9
3         3   LA    20      0      1

In [41]:
#Another Pandas joining method with fewer arguments, .join method
df_left.join(df_right)


data key  group_data
0     0   X         NaN
1     1   Y         NaN
2     2   Z         NaN
3     3   X         NaN
4     4   Y         NaN

# Concatenate[31]

## Joining DataFrames and Matrices

In [42]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [44]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
#Concatenate in Pandas
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])

In [46]:
ser1

T    0
U    1
V    2
dtype: int64

In [47]:
ser2

X    3
Y    4
dtype: int64

In [48]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [49]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [50]:
#Add keys to the concat result, use index hierarchy
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [51]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])
dframe1

X         Y         Z
0 -0.333859 -1.056626  0.004825
1  0.931793 -2.221912 -2.338476
2  0.322888 -0.331739 -0.974656
3  0.643364  0.862751  0.572245

In [52]:
dframe2

Y         Q         X
0  0.075157  2.698036  0.017927
1 -0.909758  0.165182 -0.939710
2  1.177046  2.161164  0.620204

In [53]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -0.333859 -1.056626  0.004825
1       NaN  0.931793 -2.221912 -2.338476
2       NaN  0.322888 -0.331739 -0.974656
3       NaN  0.643364  0.862751  0.572245
0  2.698036  0.017927  0.075157       NaN
1  0.165182 -0.939710 -0.909758       NaN
2  2.161164  0.620204  1.177046       NaN

In [54]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN -0.333859 -1.056626  0.004825
1       NaN  0.931793 -2.221912 -2.338476
2       NaN  0.322888 -0.331739 -0.974656
3       NaN  0.643364  0.862751  0.572245
4  2.698036  0.017927  0.075157       NaN
5  0.165182 -0.939710 -0.909758       NaN
6  2.161164  0.620204  1.177046       NaN

# More info on concatenate
url = 'http://pandas.pydata.org/pandas-docs/dev/generated/pandas.tools.merge.concat.html'

# Overlapping Indexes[32]

In [55]:
ser1 = Series([2,np.nan,4,np.nan,6,np.nan],
             index=['Q','R','S','T','U','V'])
ser1

Q    2.0
R    NaN
S    4.0
T    NaN
U    6.0
V    NaN
dtype: float64

In [56]:
ser2 = Series(np.arange(len(ser1)),dtype=np.float64,
             index=['Q','R','S','T','U','V'])
ser2

Q    0.0
R    1.0
S    2.0
T    3.0
U    4.0
V    5.0
dtype: float64

In [57]:
#Using where clause to make series:
##Where series 1 is null put in the series 2 value, otherwise put in the 
###series 1 value
Series(np.where(pd.isnull(ser1),ser2,ser1),index=ser1.index)

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [58]:
#Shortcut in Pandas using the combine first method
ser1.combine_first(ser2)

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

# Working on DataFrames

In [59]:
nan = np.nan
dframe_odds = DataFrame({'X':[1.,nan,3.,nan],
                        'Y':[nan,5.,nan,7.],
                        'Z':[nan,9.,nan,11]})

In [60]:
dframe_evens = DataFrame({'X':[2.,4.,nan,6.,8.],
                         'Y':[nan,10.,12.,14.,16.]})

In [61]:
dframe_odds

X    Y     Z
0  1.0  NaN   NaN
1  NaN  5.0   9.0
2  3.0  NaN   NaN
3  NaN  7.0  11.0

In [62]:
dframe_evens

X     Y
0  2.0   NaN
1  4.0  10.0
2  NaN  12.0
3  6.0  14.0
4  8.0  16.0

In [63]:
dframe_odds.combine_first(dframe_evens)

X     Y     Z
0  1.0   NaN   NaN
1  4.0   5.0   9.0
2  3.0  12.0   NaN
3  6.0   7.0  11.0
4  8.0  16.0   NaN